// Leaves, GP47, Qual Allowance, Discipline, Injury
(function(){
const { useState } = React;
const D = window.HR_DATA;
const { StatusDot } = window.PageA;

function Leaves() {
  const [tab, setTab] = useState("sick");
  return (
    <div className="page">
      <div className="page-head">
        <div><div className="crumbs">Welfare</div><h1>Leaves</h1></div>
        <div className="page-actions"><button className="btn">Yellow card review</button><button className="btn primary">+ Record leave</button></div>
      </div>
      <div className="tabs">
        <div className={"tab "+(tab==="sick"?"active":"")} onClick={()=>setTab("sick")}>Sick leave <span className="count">{D.SICK_LEAVES.length}</span></div>
        <div className={"tab "+(tab==="special"?"active":"")} onClick={()=>setTab("special")}>Special leave <span className="count">{D.SPECIAL_LEAVES.length}</span></div>
        <div className={"tab "+(tab==="redpt"?"active":"")} onClick={()=>setTab("redpt")}>Reduced part-time</div>
        <div className={"tab "+(tab==="replacements"?"active":"")} onClick={()=>setTab("replacements")}>Replacements</div>
      </div>
      {tab==="sick" && (
        <div className="card"><table className="table compact">
          <thead><tr><th>ID Card</th><th>Name</th><th>Year</th><th>From</th><th>To</th><th className="right">Days</th><th>Paid</th><th>Type</th></tr></thead>
          <tbody>{D.SICK_LEAVES.map(s=>(
            <tr key={s.id}><td className="id">{s.idCard}</td><td>{s.name}</td><td className="num">{s.year}</td><td className="num">{s.from}</td><td className="num">{s.to}</td><td className="num right">{s.totalDays}</td><td>{s.paidUnpaid==="Paid"?<span className="tag green">Paid</span>:<span className="tag amber">Unpaid</span>}</td><td>{s.type}</td></tr>
          ))}</tbody>
        </table></div>
      )}
      {tab==="special" && (
        <div className="card"><table className="table compact">
          <thead><tr><th>ID Card</th><th>Name</th><th>From</th><th>To</th><th>Type</th><th className="right">Days</th><th>Approved by</th></tr></thead>
          <tbody>{D.SPECIAL_LEAVES.map(s=>(
            <tr key={s.id}><td className="id">{s.idCard}</td><td>{s.name}</td><td className="num">{s.from}</td><td className="num">{s.to}</td><td><span className="tag blue">{s.type}</span></td><td className="num right">{s.daysTaken}</td><td>{s.approvedBy}</td></tr>
          ))}</tbody>
        </table></div>
      )}
      {tab==="redpt" && <div className="card card-body"><div className="empty">No active reduced part-time arrangements.</div></div>}
      {tab==="replacements" && <div className="card card-body"><div className="empty">Replacement teacher tracking — link to Recruitment supply seniority list.</div></div>}
    </div>
  );
}

function GP47() {
  const [step, setStep] = useState(0);
  const steps = ["Select person","Service component","Leaves component","Discipline check","Generate"];
  return (
    <div className="page">
      <div className="page-head"><div><div className="crumbs">Welfare</div><h1>GP47 Form</h1></div><div className="page-actions"><button className="btn">View past GP47s</button><button className="btn primary">+ New GP47</button></div></div>
      <div className="alert" style={{marginBottom:12}}><span className="ico">ℹ</span><div><strong>GP47</strong> is the official combined service-and-leave history form. Generated by combining service eventsrvice, special/reduced leaves, and disciplinary entries — sent to the government Records Section.</div></div>
      <div className="stepper" style={{marginBottom:12}}>{steps.map((s,i)=>(<div key={i} className={"step "+(i<step?"done":i===step?"active":"")}><div className="n">Step {i+1}</div><div className="t">{s}</div></div>))}</div>
      <div className="split" style={{alignItems:"flex-start"}}>
        <div className="card"><div className="card-head"><h2>Combined view — Roberta Camilleri (0259684M)</h2></div>
          <table className="table compact">
            <thead><tr><th>Source</th><th>From</th><th>To</th><th>Detail</th></tr></thead>
            <tbody>
              {D.PRS_RECORDS.map(r=>(<tr key={"p"+r.id}><td><span className="tag blue">Service</span></td><td className="num">{r.from}</td><td className="num">{r.to||"—"}</td><td>{r.position} — Scale {r.scale} — {r.paypoint}</td></tr>))}
              <tr><td><span className="tag amber">Special</span></td><td className="num">2016-04-01</td><td className="num">2016-09-30</td><td>Maternity leave (paid) — 26 weeks</td></tr>
              <tr><td><span className="tag amber">Special</span></td><td className="num">2019-09-01</td><td className="num">2020-08-31</td><td>Parental leave (unpaid) — 12 months</td></tr>
              <tr><td><span className="tag gray">Red PT</span></td><td className="num">2020-09-01</td><td className="num">2021-08-31</td><td>Reduced hours (60%)</td></tr>
            </tbody>
          </table>
        </div>
        <div className="col-flex">
          <div className="card"><div className="card-head"><h2>Form actions</h2></div><div className="card-body">
            <button className="btn primary" style={{width:"100%", marginBottom:6}} onClick={()=>setStep(Math.min(4, step+1))}>Advance step →</button>
            <button className="btn" style={{width:"100%", marginBottom:6}}>Preview as PDF</button>
            <button className="btn" style={{width:"100%"}}>Send to Records Section</button>
          </div></div>
          <div className="card"><div className="card-head"><h2>Validation</h2></div><div className="card-body">
            <div className="kv">
              <dt>Service entries</dt><dd>4 ✓</dd>
              <dt>Leave entries</dt><dd>3 ✓</dd>
              <dt>Discipline expiry</dt><dd>OK ✓</dd>
              <dt>Address current</dt><dd>OK ✓</dd>
              <dt>Spouse details</dt><dd><span className="tag amber">Verify</span></dd>
            </div>
          </div></div>
        </div>
      </div>
    </div>
  );
}

function QualAllowance() {
  return (
    <div className="page">
      <div className="page-head"><div><div className="crumbs">Pay & progression</div><h1>Qualification Allowance</h1></div><div className="page-actions"><button className="btn">MQF reference</button><button className="btn primary">+ New application</button></div></div>
      <div className="stats" style={{marginBottom:12}}>
        <div className="stat"><div className="lbl">Total applications</div><div className="val">{D.QUAL_ALLOWANCE.length}</div></div>
        <div className="stat"><div className="lbl">PSD/DCS approved</div><div className="val">{D.QUAL_ALLOWANCE.filter(q=>q.psdApproval).length}</div></div>
        <div className="stat"><div className="lbl">Sent to SRS</div><div className="val">{D.QUAL_ALLOWANCE.filter(q=>q.sentToSRS).length}</div></div>
        <div className="stat"><div className="lbl">Audited</div><div className="val">{D.QUAL_ALLOWANCE.filter(q=>q.audited).length}</div></div>
      </div>
      <div className="card"><table className="table compact">
        <thead><tr><th>ID</th><th>Name</th><th>Grade</th><th>Qualification</th><th>Awarding body</th><th>MQF</th><th>WEF</th><th className="right">Amount</th><th>PSD</th><th>SRS</th><th>Audited</th></tr></thead>
        <tbody>{D.QUAL_ALLOWANCE.map(q=>(
          <tr key={q.id}><td className="id">{q.idCard}</td><td>{q.name}</td><td>{q.grade}</td><td>{q.title}</td><td>{q.awardingBody}</td><td className="num">{q.mqf}</td><td className="num">{q.effectiveDate}</td><td className="num right">€{q.amount}</td><td>{q.psdApproval?<span className="tag green">✓</span>:<span className="tag amber">…</span>}</td><td>{q.sentToSRS?<span className="tag green">✓</span>:<span className="muted">—</span>}</td><td>{q.audited?<span className="tag green">✓</span>:<span className="muted">—</span>}</td></tr>
        ))}</tbody>
      </table></div>
    </div>
  );
}

function Discipline() {
  return (
    <div className="page">
      <div className="page-head"><div><div className="crumbs">Welfare</div><h1>Discipline</h1></div><div className="page-actions"><button className="btn">Expiry check</button><button className="btn primary">+ New case</button></div></div>
      <div className="card"><table className="table compact">
        <thead><tr><th>ID Card</th><th>Name</th><th>Opened</th><th>Type</th><th>Status</th><th>Expiry</th><th>Officer</th><th></th></tr></thead>
        <tbody>{D.DISCIPLINE.map(d=>(
          <tr key={d.id}><td className="id">{d.idCard}</td><td>{d.name}</td><td className="num">{d.openedOn}</td><td><span className="tag amber">{d.type}</span></td><td><StatusDot status={d.status}/></td><td className="num">{d.expiryDate}</td><td>{d.officer}</td><td><button className="btn sm">Open</button></td></tr>
        ))}</tbody>
      </table></div>
      <div className="alert amber" style={{marginTop:12}}><span className="ico">⚠</span><div>Disciplinary entries impact remarks and the GP47 form. Expiry dates trigger automatic removal from the public-facing record.</div></div>
    </div>
  );
}

function Injury() {
  return (
    <div className="page">
      <div className="page-head"><div><div className="crumbs">Welfare</div><h1>Injury</h1></div><div className="page-actions"><button className="btn">Board members</button><button className="btn primary">+ New report</button></div></div>
      <div className="stats" style={{marginBottom:12}}>
        <div className="stat"><div className="lbl">Total reports</div><div className="val">{D.INJURIES.length}</div></div>
        <div className="stat"><div className="lbl">Pending board</div><div className="val">{D.INJURIES.filter(i=>i.status==="Pending").length}</div></div>
        <div className="stat"><div className="lbl">Approved</div><div className="val">{D.INJURIES.filter(i=>i.status==="Approved").length}</div></div>
        <div className="stat"><div className="lbl">Notification sent</div><div className="val">{D.INJURIES.filter(i=>i.notificationSent).length}</div></div>
      </div>
      <div className="card"><table className="table compact">
        <thead><tr><th>ID Card</th><th>Name</th><th>Date</th><th>Pay point</th><th>Type</th><th>Body part</th><th>Status</th><th>Notification</th></tr></thead>
        <tbody>{D.INJURIES.map(i=>(
          <tr key={i.id}><td className="id">{i.idCard}</td><td>{i.name}</td><td className="num">{i.injuryDate}</td><td className="id">{i.paypoint}</td><td>{i.type}</td><td>{i.bodyPart}</td><td><StatusDot status={i.status}/></td><td>{i.notificationSent?<span className="tag green">✓ Sent</span>:<span className="tag amber">Pending</span>}</td></tr>
        ))}</tbody>
      </table></div>
    </div>
  );
}

window.PageC = { Leaves, GP47, QualAllowance, Discipline, Injury };
})();
